name: production-deployment
run-name: ${{ github.actor }} is deploying to production
on:
    workflow_dispatch: 
        inputs:
            version:
                description: 'Version to deploy'
                required: true

jobs:
  deploy:
    if: ${{  github.event.inputs.version }}
    name: Deploy to production Environment
    environment: production
    runs-on: ubuntu-latest
    steps:
      - name: Regex Match Input
        id: regex_check
        uses: actions-ecosystem/action-regex-match@v2
        with:
            text: ${{ github.event.inputs.version }}
            regex: '^v.[0-9]+.[0-9]+.[0-9]+'
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Deploy application
        run: |
          echo "Deploying version $TAG_NAME to the ${{ github.environment }} environment"
    timeout-minutes: 1
