
name: Deploy to Development
on:
    push:
        tags:
            - 'v*.*.*'
jobs:
    deploy:
        name: Deploy to Development Environment
        environment: development
        if: startsWith(github.ref, 'refs/tags/v')
        runs-on: ubuntu-latest
        steps:
            - name: Checkout code
              uses: actions/checkout@v2
            - name: Deploy application
              run: echo "Deploying version ${{ github.ref }} to the ${{ github.environment }} environment"