name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        type: choice
        options:
          - development
          - production
  push:
    tags:
      - '*'

jobs:
  deploy:
    name: Deploy to Development Environment
    environment: ${{ inputs.environment || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Deploy application
        run: |
          echo "Deploying version ${{ github.ref_name }} to the ${{ input.environment }} environment"
    timeout-minutes: 1
