name: Deploy to Development
on:
  workflow_run:
    workflows: ["Create/update tag"]
    types:
      - completed

jobs:
  deploy:
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    name: Deploy to Development Environment
    environment: development
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Fetch latest tag
        id: get_tag
        run: |
          git fetch --tags
          echo "TAG_NAME=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
      - name: Deploy application
        run: |
          echo "Deploying version $TAG_NAME to the ${{ github.environment }} environment"