name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        type: choice
        options:
          - development
          - production
      version:
        description: 'The version to deploy'
        required: false
        type: string
  workflow_run: 
    workflows: ["Create/update tag"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Development Environment
    env:
      version: ${{ inputs.version || git describe --tags --abbrev=0 }}
    environment: ${{ inputs.environment || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Deploy application
        run: |
          echo "Deploying version ${{ inputs.version }} to the ${{ inputs.environment }} environment"
    timeout-minutes: 1
