name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        type: choice
        options:
          - development
          - production
      version:
        description: 'The version to deploy'
        required: false
        type: string
  workflow_run: 
    workflows: ["Create/update tag"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Development Environment
    environment: ${{ inputs.environment || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set version (user input or tag ref)
        id: set_version
        run: |
          if [ -n "${{ inputs.version }}" ]; then
            echo "version=${{ inputs.version }}" >> $GITHUB_ENV
          else
            git fetch --tags
            TAG=$(git tag --points-at ${{ github.event.workflow_run.head_sha }} | head -n1)
            echo "version=${TAG}" >> $GITHUB_ENV
          fi
      - name: Deploy application
        run: |
          echo "Deploying version $version to the ${{ inputs.environment || 'development' }} environment"
    timeout-minutes: 1
