name: deploy
on:
  workflow_dispatch:
    inputs:
      environment:
        description: 'The environment to deploy to'
        required: false
        type: choice
        options:
          - development
          - production
      version:
        description: 'The version to deploy'
        required: false
        type: string
  workflow_run: 
    workflows: ["Create/update tag"]
    types:
      - completed

jobs:
  deploy:
    name: Deploy to Development Environment
    environment: ${{ inputs.environment || 'development' }}
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-tags: true
          fetch-depth: 0
      - name: Set version (user input or latest tag)
        id: set_version
        run: |
            if [ -n "${{ inputs.version }}" ]; then
              echo "version=${{ inputs.version }}" >> $GITHUB_ENV
            else
              git fetch --tags
              echo "version=$(git describe --tags --abbrev=0)" >> $GITHUB_ENV
            fi
      - name: Deploy application
        run: |
          echo "Deploying version $version to the ${{ inputs.environment }} environment"
    timeout-minutes: 1
