name: Create/update tag
on:
  push:
    branches: 
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
      - name: Get next sematic version
        id: semver
        uses: ActionsDesk/semver@v1
       
