name: Create/update tag
on:
  push:
    branches: 
      - main
jobs:
  create-tag:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
        with:
          fetch-depth: 0
      - name: Get next sematic version
        id: semver
        uses: paulhatch/semantic-version@v5.4.0
        with:
              tag_prefix: "v"
              major_pattern: "MAJOR"
              minor_pattern: "MINOR"
              patch_pattern: "PATCH"
              version_format: "v${major}.${minor}.${patch}"
              bump_each_commit: false
              search_commit_body: true
      - name: Create GitHub Release
        uses: softprops/action-gh-release@v2
        if: startsWith(github.ref, 'refs/tags/v') # Only create release if a new tag was pushed
        with:
          tag_name: ${{ steps.version.outputs.version }}
          name: Release ${{ steps.version.outputs.version }}
          body: |
            Automated release for version ${{ steps.version.outputs.version }} 
       
